before:
  hooks:
    - go vet ./...
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - main: ./main.go
    id: "core"
    binary: goplug
    goos:
      - linux
      - darwin
      - windows
    ignore:
      - goos: darwin
        goarch: arm64
    env:
      - CGO_ENABLED=0
  - main: ./plugins/sql/main.go
    id: "plugin-sql"
    binary: plugin-sql
    goos:
      - linux
      - darwin
      - windows
    ignore:
      - goos: darwin
        goarch: arm64
    env:
      - CGO_ENABLED=0
archives:
  - replacements:
      darwin: macos
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
