project_name: goplug

before:
  hooks:
    - go vet ./...
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - main: ./main.go
    id: "core"
    binary: goplug
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: arm64
    env:
      - CGO_ENABLED=0
  - main: ./plugins/sql/main.go
    id: "plugin-sql"
    binary: plugin-sql
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: arm64
    env:
      - CGO_ENABLED=0
archives:
  - replacements:
      darwin: macos
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  -
    goos: linux
    goarch: amd64
    ids:
      - core
      - plugin-sql
    dockerfile: Dockerfile
    image_templates:
      - 'ghcr.io/kushsharma/{{.ProjectName}}:{{ .Tag }}-amd64'

brews:
  -
    name: goplug
    ids:
      - core
      - plugin-sql
    tap:
      owner: kushsharma
      name: taps
    license: "MIT"
    description: "Testing goplug"
    commit_author:
      name: optimus
      email: kush.sharma@gojek.com